/**
 * Regenerate src/lib/import/lanes.ts from lanes.config.json.
 *
 * Resolves each configured port pair to coordinates (from ports.data.json, via
 * the app's own lookup so aliases and canonicalisation match), routes them over
 * the searoute marine network (gen_lanes.py), and writes the lane table the map
 * reads. Run with: npm run lanes:generate
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { lookupPort, canonicalPortKey } from "../../src/lib/import/ports";

const here = path.dirname(fileURLToPath(import.meta.url));
const configPath = path.join(here, "lanes.config.json");
const pairsTmp = path.join(here, ".pairs.json");
const lanesTmp = path.join(here, ".lanes.json");
const outPath = path.join(here, "..", "..", "src", "lib", "import", "lanes.ts");

const config = JSON.parse(fs.readFileSync(configPath, "utf8")) as {
  pairs: { pol: string; pod: string }[];
};

// Resolve coordinates for every configured pair; skip and warn on unknown ports.
const pairs: { key: string; pol: [number, number]; pod: [number, number] }[] = [];
const missing = new Set<string>();
const seen = new Set<string>();
for (const { pol, pod } of config.pairs) {
  const o = lookupPort(pol);
  const d = lookupPort(pod);
  const pk = canonicalPortKey(pol);
  const dk = canonicalPortKey(pod);
  if (!o.known) missing.add(pk);
  if (!d.known) missing.add(dk);
  if (!o.known || !d.known) continue;
  const key = `${pk}__${dk}`;
  if (seen.has(key)) continue;
  seen.add(key);
  pairs.push({ key, pol: [o.point.lng, o.point.lat], pod: [d.point.lng, d.point.lat] });
}

if (missing.size) {
  console.warn(
    `Skipped pairs with unmapped ports: ${[...missing].sort().join(", ")}.\n` +
      `Add them first with: npm run lanes:add-port -- --name "<PORT>" --code <UNLOCODE> --lat <lat> --lng <lng>`,
  );
}

fs.writeFileSync(pairsTmp, JSON.stringify(pairs));

// Pick a Python that has searoute: prefer a local venv, fall back to python3.
const venvPython = path.join(here, "venv", "bin", "python");
const python = fs.existsSync(venvPython) ? venvPython : "python3";
const run = spawnSync(python, [path.join(here, "gen_lanes.py"), pairsTmp, lanesTmp], {
  stdio: ["ignore", "inherit", "inherit"],
});
if (run.status !== 0) {
  fs.rmSync(pairsTmp, { force: true });
  console.error("\nRouting failed. See scripts/lanes/README.md for the searoute setup.");
  process.exit(1);
}

const lanes = JSON.parse(fs.readFileSync(lanesTmp, "utf8")) as Record<
  string,
  { pts: [number, number][]; km: number }
>;

// Emit lanes.ts: keys sorted, points as [lat, lng], consecutive duplicates dropped.
const lines: string[] = [
  "// AUTO-GENERATED by scripts/lanes/generate.mts — do not edit by hand.",
  "// Real maritime routes between the port pairs in lanes.config.json, computed",
  "// with the searoute marine network so the map draws each sea shipment along an",
  "// actual shipping lane (through Malacca, Suez, the Torres Strait, and so on)",
  "// instead of a straight line across land. Train and air legs draw straight,",
  "// which is correct for overland and flight legs.",
  "//",
  `// ${Object.keys(lanes).length} lanes. Regenerate with: npm run lanes:generate`,
  "// Keys are `${canonicalPol}__${canonicalPod}`; values are [lat, lng] points.",
  "",
  "export const SEA_LANES: Record<string, [number, number][]> = {",
];
for (const key of Object.keys(lanes).sort()) {
  const seq: [number, number][] = [];
  for (const [lng, lat] of lanes[key].pts) {
    const p: [number, number] = [Number(lat.toFixed(3)), Number(lng.toFixed(3))];
    const last = seq[seq.length - 1];
    if (last && last[0] === p[0] && last[1] === p[1]) continue;
    seq.push(p);
  }
  lines.push(`  "${key}": [${seq.map(([a, b]) => `[${a}, ${b}]`).join(", ")}],`);
}
lines.push("};", "");

fs.writeFileSync(outPath, lines.join("\n"));
fs.rmSync(pairsTmp, { force: true });
fs.rmSync(lanesTmp, { force: true });
console.log(`Wrote ${path.relative(process.cwd(), outPath)} with ${Object.keys(lanes).length} lanes.`);
